from typing import List

import fire

from granular.train_stage1 import stage1
from granular.train_stage2 import stage2
from granular.train_stage3 import stage3


class Pipeline(object):
    def __init__(self):
        self.stage1 = Stage1()
        self.stage2 = Stage2()
        self.stage3 = Stage3()

    def all(
        self,
        data_dir: str,
        name=None,
        classes: List[str] = [],
        gpus=1,
        profiler=False,
        out_dir="modelzoo",
        # waveform training config
        waveform_name=None,
        waveform_continue_train=False,
        waveform_batch_size=24,
        waveform_learning_rate=0.0002,
        waveform_max_steps=300000,
        waveform_num_workers=2,
        waveform_precision=32,
        waveform_tar_beta=0.003,
        waveform_beta_steps=500,
        waveform_tar_l=1.1,
        # waveform model config
        waveform_amplitude_norm=False,
        waveform_channels=128,
        waveform_env_dist=0,
        waveform_h_dim=512,
        waveform_kernel_size=9,
        waveform_l_grain=2048,
        waveform_log_dist=0.0,
        waveform_mel_dist=True,
        waveform_mel_scales=[2048, 1024],
        waveform_n_convs=3,
        waveform_n_linears=3,
        waveform_normalize_ola=True,
        waveform_pp_chans=5,
        waveform_pp_ker=65,
        waveform_silent_reject=[0.2, 0.2],
        waveform_spec_power=1,
        waveform_sr=22050,
        waveform_stft_scales=[2048, 1024, 512, 256],
        waveform_stride=4,
        waveform_z_dim=128,
        # latent training config
        latent_name=None,
        latent_batch_size=32,
        latent_learning_rate=0.0002,
        latent_max_steps=500000,
        latent_tar_beta=0.01,
        latent_beta_steps=500,
        latent_num_workers=2,
        latent_precision=32,
        # latent model config
        latent_e_dim=256,
        latent_h_dim=512,
        latent_n_RNN=1,
        latent_n_linears=2,
        latent_rnn_type="LSTM",
        # hierarchical training config
        hierarchical_batch_size=16,
        hierarchical_learning_rate=2e-6,  # here is the fixed learning rate at the end of the decay of the sub-network pretraining
        hierarchical_w_beta=0.0,
        hierarchical_l_beta=0.0,
        hierarchical_max_steps=100000,
        hierarchical_num_workers=2,
        hierarchical_precision=32,
    ):
        self.stage1.run(
            data_dir=data_dir,
            classes=classes,
            name=waveform_name if waveform_name is not None else f"granular_waveform_{name}",
            continue_train=waveform_continue_train,
            batch_size=waveform_batch_size,
            learning_rate=waveform_learning_rate,
            max_steps=waveform_max_steps,
            num_workers=waveform_num_workers,
            gpus=gpus,
            precision=waveform_precision,
            profiler=profiler,
            out_dir=out_dir,
            tar_beta=waveform_tar_beta,
            beta_steps=waveform_beta_steps,
            tar_l=waveform_tar_l,
            amplitude_norm=waveform_amplitude_norm,
            channels=waveform_channels,
            env_dist=waveform_env_dist,
            h_dim=waveform_h_dim,
            kernel_size=waveform_kernel_size,
            l_grain=waveform_l_grain,
            log_dist=waveform_log_dist,
            mel_dist=waveform_mel_dist,
            mel_scales=waveform_mel_scales,
            n_convs=waveform_n_convs,
            n_linears=waveform_n_linears,
            normalize_ola=waveform_normalize_ola,
            pp_chans=waveform_pp_chans,
            pp_ker=waveform_pp_ker,
            silent_reject=waveform_silent_reject,
            spec_power=waveform_spec_power,
            sr=waveform_sr,
            stft_scales=waveform_stft_scales,
            stride=waveform_stride,
            z_dim=waveform_z_dim,
        )
        self.stage2.run(
            data_dir=data_dir,
            name=latent_name if latent_name is not None else f"granular_latent_{name}",
            waveform_name=waveform_name if waveform_name is not None else f"granular_waveform_{name}",
            batch_size=latent_batch_size,
            learning_rate=latent_learning_rate,
            max_steps=latent_max_steps,
            tar_beta=latent_tar_beta,
            beta_steps=latent_beta_steps,
            conditional=len(classes) != 0,
            num_workers=latent_num_workers,
            gpus=gpus,
            precision=latent_precision,
            profiler=profiler,
            out_dir=out_dir,
            e_dim=latent_e_dim,
            h_dim=latent_h_dim,
            n_RNN=latent_n_RNN,
            n_linears=latent_n_linears,
            rnn_type=latent_rnn_type,
        )
        self.stage3.run(
            data_dir=data_dir,
            latent_name=latent_name if latent_name is not None else f"granular_latent_{name}",
            waveform_name=waveform_name if waveform_name is not None else f"granular_waveform_{name}",
            batch_size=hierarchical_batch_size,
            learning_rate=hierarchical_learning_rate,
            w_beta=hierarchical_w_beta,
            l_beta=hierarchical_l_beta,
            max_steps=hierarchical_max_steps,
            num_workers=hierarchical_num_workers,
            gpus=gpus,
            precision=hierarchical_precision,
            profiler=profiler,
            out_dir=out_dir,
        )


class Stage1(object):
    def run(
        self,
        data_dir: str,
        classes=[],
        name=None,
        continue_train=False,
        batch_size=24,
        learning_rate=0.0002,
        max_steps=300000,
        num_workers=2,
        gpus=1,
        precision=32,
        profiler=False,
        out_dir="modelzoo",
        tar_beta=0.003,
        beta_steps=500,
        tar_l=1.1,
        # waveform model config
        amplitude_norm=False,
        channels=128,
        env_dist=0,
        h_dim=512,
        kernel_size=9,
        l_grain=2048,
        log_dist=0.0,
        mel_dist=True,
        mel_scales=[2048, 1024],
        n_convs=3,
        n_linears=3,
        normalize_ola=True,
        pp_chans=5,
        pp_ker=65,
        silent_reject=[0.2, 0.2],
        spec_power=1,
        sr=22050,
        stft_scales=[2048, 1024, 512, 256],
        stride=4,
        z_dim=128,
    ):
        return stage1(
            classes=classes,
            data_dir=data_dir,
            name=name,
            continue_train=continue_train,
            batch_size=batch_size,
            learning_rate=learning_rate,
            max_steps=max_steps,
            num_workers=num_workers,
            gpus=gpus,
            precision=precision,
            profiler=profiler,
            out_dir=out_dir,
            tar_beta=tar_beta,
            beta_steps=beta_steps,
            tar_l=tar_l,
            amplitude_norm=amplitude_norm,
            channels=channels,
            env_dist=env_dist,
            h_dim=h_dim,
            kernel_size=kernel_size,
            l_grain=l_grain,
            log_dist=log_dist,
            mel_dist=mel_dist,
            mel_scales=mel_scales,
            n_convs=n_convs,
            n_linears=n_linears,
            normalize_ola=normalize_ola,
            pp_chans=pp_chans,
            pp_ker=pp_ker,
            silent_reject=silent_reject,
            spec_power=spec_power,
            sr=sr,
            stft_scales=stft_scales,
            stride=stride,
            z_dim=z_dim,
        )


class Stage2(object):
    def run(
        self,
        data_dir: str,
        name=None,
        waveform_name=None,
        batch_size=32,
        learning_rate=0.0002,
        max_steps=500000,
        tar_beta=0.01,
        beta_steps=500,
        conditional=False,
        num_workers=2,
        gpus=1,
        precision=32,
        profiler=False,
        out_dir="modelzoo/",
        # latent model config
        e_dim=256,
        h_dim=512,
        n_RNN=1,
        n_linears=2,
        rnn_type="LSTM",
    ):
        return stage2(
            data_dir=data_dir,
            name=name,
            waveform_name=waveform_name,
            batch_size=batch_size,
            learning_rate=learning_rate,
            max_steps=max_steps,
            tar_beta=tar_beta,
            beta_steps=beta_steps,
            conditional=conditional,
            num_workers=num_workers,
            gpus=gpus,
            precision=precision,
            profiler=profiler,
            out_dir=out_dir,
            e_dim=e_dim,
            h_dim=h_dim,
            n_RNN=n_RNN,
            n_linears=n_linears,
            rnn_type=rnn_type,
        )


class Stage3(object):
    def run(
        self,
        data_dir: str,
        latent_name=None,
        waveform_name=None,
        batch_size=16,
        learning_rate=2e-6,  # here is the fixed learning rate at the end of the decay of the sub-network pretraining
        w_beta=0.0,
        l_beta=0.0,
        max_steps=100000,
        num_workers=2,
        gpus=1,
        precision=32,
        profiler=False,
        out_dir="modelzoo",
    ):
        return stage3(
            data_dir=data_dir,
            latent_name=latent_name,
            waveform_name=waveform_name,
            batch_size=batch_size,
            learning_rate=learning_rate,
            w_beta=w_beta,
            l_beta=l_beta,
            max_steps=max_steps,
            num_workers=num_workers,
            gpus=gpus,
            precision=precision,
            profiler=profiler,
            out_dir=out_dir,
        )


if __name__ == "__main__":
    fire.Fire(Pipeline)
